### ISSUE TITLE
default nudging towards @MainActor in UI /  keeping the same structured context

### ISSUE THREAD

**Issue by adriansergheev** [apple/swift-migration-guide#108]
there are two ideas which i found helpful while building with swift's concurrency model:
- `@MainActor` annotation for the concept of `"model"` `"viewModel"` or anything which directly enables UI
- to try keeping work in _one_ structured concurrency context for as long as possible, and in general, spawn as little `Task's` as building the feature allows

for example, instead of:
```
  var body: some View {
    Text("Hello World")
      .task {
        Task {
          model.runSomethingAsync()
        }
      }
  }
```

do
```
var body: some View {
  Text("Hello World")
    .task {
      await model.runSomethingAsync()
    }
}
```
perhaps not the best example here since Task inherits the actor, though, the way i understand it, if the view gets out of scope cancellation would be preserved only in the second example while first would run to completion 

is any of this worth having in the guide? if yes, will try to conjure something around it

**Comment by mattmassicotte** [comment]
I think these are both great observations. And you are correct: `Task` does inherit actor context and must be explicitly cancelled.

It's totally fine to have non-isolated types you use with a UI component. But, if you begin introducing concurrency into those types, the compiler will prevent you from doing anything invalid. So, I don't know if any nudging in this area is actually required. The compiler will do it for you. Plus, SwiftUI's API has been improved significantly with the SDKs in Xcode 16 which I think will further limit confusion that has been allowed to build up.

I have also found that, in general, a single async context as deep in the call stack as possible is preferrable. This also ties in quite well with #25.

Now, higher-level. This guide is about the language as a whole, not a specific framework. But, if you want to think about where/how to include a discussion about sync -> async transitions in more abstract terms, it would be very welcome!

**Comment by adriansergheev** [comment]
https://github.com/apple/swift-migration-guide/issues/25
