### ISSUE TITLE
What is the difference between "Limiting concurrency using Task Groups" in Incremental Adoption and "Limiting concurrency using Task Groups" in Runtime Behavior

### ISSUE THREAD

**Issue by stzn** [apple/swift-migration-guide#134]
What is the difference between the “Limiting concurrency using Task Groups” section in Incremental Adoption and the “Limiting concurrency using Task Groups” section in Runtime Behavior?

The “Limiting concurrency using Task Groups” section appears in both Incremental Adoption and Runtime Behavior.

https://github.com/apple/swift-migration-guide/blob/main/Guide.docc/IncrementalAdoption.md#limiting-concurrency-using-task-groups
https://github.com/apple/swift-migration-guide/blob/main/Guide.docc/RuntimeBehavior.md#limiting-concurrency-using-task-groups

According to the PR, it seems correct that this section is included in Runtime Behavior.
https://github.com/apple/swift-migration-guide/pull/56#issuecomment-2167188439

Why is “Limiting concurrency using Task Groups” included in both documents, and what is the difference between the two?

**Comment by mattmassicotte** [comment]
I'm not sure exactly how this happened. @ktoso which of these should we keep?

**Comment by ktoso** [comment]
I think it should be in runtime behavior.

Sorry for slow replies I'm sick right now

**Comment by stzn** [comment]
> Sorry for slow replies I'm sick right now

Please take care of yourself.

Thank you for the replay!

> I think it should be in runtime behavior.

So, can we remove the section from Incremental Adoption?

**Comment by stzn** [comment]
I think it was fixed in https://github.com/apple/swift-migration-guide/pull/139. Thank you!

Can we close this issue?

**Comment by mattmassicotte** [comment]
Ahh yes it was. Thank you!
