### ISSUE TITLE
Default language mode in SwiftPM 6.0 tools version

### ISSUE THREAD

**Issue by bnbarham** [apple/swift-migration-guide#17]
Not quite sure whether this belongs, possibly in common problems? The default language mode for `// swift-tools-version: 6.0` in SwiftPM is also 6.0. If that causes issues, users can work around it by specifying a top level `swiftLanguageVersion: [.v5]` for their package.

**Comment by mattmassicotte** [comment]
Thank you for pointing this out!

Having some suggestions on how to adapt `Package.swift` files for maximum compatibility seems like it would be really useful. I was even struggling with it for this repo yesterday!

**Comment by bnbarham** [comment]
There's also now a target level `swiftLanguageVersion` that can be used for incremental migration ([SE-0435](https://github.com/apple/swift-evolution/blob/main/proposals/0435-swiftpm-per-target-swift-language-version-setting.md)).

**Comment by mattmassicotte** [comment]
Yes I am aware, and totally agree that'll become very commonly-used!

**Comment by mattmassicotte** [comment]
For real this time
