### ISSUE TITLE
Dynamic isolation examples

### ISSUE THREAD

**Issue by dempseyatgithub** [apple/swift-migration-guide#37]
In the Data Race Safety article, a lot of emphasis is placed in the Data Isolation section on static vs dynamic data isolation.

The rest of the article focuses mainly on declarations, which would be considered static.

It seems like there should be some concrete examples of dynamic isolation as well.

EDIT: I just noticed there is a section on Dynamic Isolation in the Incremental Adoption article. Maybe there should at least be a link from the Data Race Safety article to that section.

Something like:
'For more details about dynamic isolation, see the Dynamic Isolation section in Incremental Adoption'

**Comment by mattmassicotte** [comment]
Yeah, this is a good point. A link is a great idea.

**Comment by mattmassicotte** [comment]
Link added. Thanks again for the suggestion!
