### ISSUE TITLE
Add an explanation of the difference between compiler version and language mode

### ISSUE THREAD

**Issue by dempseyatgithub** [apple/swift-migration-guide#43]
Somewhere up front it would probably make sense to explain the difference between these two, and then possibly also spell out how each is referred to in the guide.

For example, I have seen a bare 'Swift 6' in a few places. Something up front that makes it clear that refers to the language mode would be helpful.

**Comment by mattmassicotte** [comment]
Ohh yes very good point.

**Comment by mattmassicotte** [comment]
Addressed by #45
