### ISSUE TITLE
More dynamic isolation content

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift-migration-guide#57]
I removed some use of `nonisolated`/`assumeIsolated` in the common errors section with #53 . But, these are still important concepts that definitely still need a place somewhere.

**Comment by ktoso** [comment]
This is semi related I suppose #60 since it shows the dynamic isolation injected between obj-c calls -- they're effectively exactly the assumeIsolated call

**Comment by mattmassicotte** [comment]
Yes! I really also want a section that covers this explicitly, as well as `GlobalActor.run`. But its great to see it in more places to get a better feel for the kinds of situations where it can help.
