### ISSUE TITLE
How to workaround missing @Sendable

### ISSUE THREAD

**Issue by ktoso** [apple/swift-migration-guide#63]
@hborla and me were just chatting and another good chapter idea came up

```
@MainActor class MyClass {
  func useCallback() {
     doSomethingAsync {
        // this is called back on some background queue or somewhere else but it's missing @Sendable so the isolation checker infers @MainActor and crashes when it's not called on the main actor
     }
  }
}
```

The workaround is this
```
@MainActor class MyClass {
  func useCallback() {
     doSomethingAsync { @Sendable in
     }
  }
}
```

But the @Sendable really should be in the signature of doSomethingAsync

**Comment by mattmassicotte** [comment]
hmmm ok yes this is really important

**Comment by mattmassicotte** [comment]
I want to be sure I understand this example. I attempted to re-construct this in code, but I am not able to reproduce a crash. Instead, I get the following logging in Swift 6 mode:

`warning: data race detected: @MainActor function at Swift6Examples/Globals.swift:70 was not called on the main thread`

I get no logging at all in Swift 5. Is this what we are talking about?

**Comment by mattmassicotte** [comment]
Sounds like the lack of crash may be related to the standard library I currently have installed. I'm doing all my testing with macOS 14.5 (23F79). I think everything is fine here. Even though the runtime behavior may be OS-dependent the wording in the guide is not wrong.
