### ISSUE TITLE
Global variables section should suggest computed variables in some cases

### ISSUE THREAD

**Issue by Azoy** [apple/swift-migration-guide#74]
True constants like:
```swift
var someConstant = 0xFF
```
should suggest both `let` and a computed property as solutions to making this concurrency safe. IMO the computed property for these cases is highly preferred because declaring data in your binary for a constant int is silly vs. a computed property who declares code. In the latter case the original definition of the function can be dead stripped because the compiler will most likely replace all calls to this function by inlining the value into callers. 

```swift
var someConstant: Int {
  0xFF
}
```

**Comment by mattmassicotte** [comment]
I think suggesting a computed property is a totally idea.

My guess would have been a constant would be inlined in exactly the same ways!

**Comment by Azoy** [comment]
It can be inlined the same! It just doesn't remove the original data definition of the variable and emits it in your binary unlike the computed property which is a function whose original definition can totally be removed in binaries.

**Comment by mattmassicotte** [comment]
Ah ha - well that makes sense!
