### ISSUE TITLE
Global mutable integers should mention atomics

### ISSUE THREAD

**Issue by Azoy** [apple/swift-migration-guide#75]
The global integer example
```swift
var supportedStyleCount = 42
```
mentions that one solution is to just isolate it to the `@MainActor`. This is one solution, but an alternative is to just wrap this integer in `Atomic`. A downside to this approach is that one must think about the memory orderings for all of the atomic operations, but in simple cases (like a global integer counter) these accesses can just be `relaxed`.
```swift
let supportedStyleCount = Atomic<Int>(42)

func printStyleCount() {
  print(supportedStyleCount.load(ordering: .relaxed))
}

func addStyle() {
  supportedStyleCount.wrappingAdd(1, ordering: .relaxed)
}
```
This has the advantage of being accessible regardless of isolation domain, doesn't do any potential hops, and compiles to a single instruction.

Perhaps this should be in a more manual synchronization section however.

**Comment by mattmassicotte** [comment]
Yeah. I do think it is reasonable to mention atomics. But, also yes, that disadvantage is substantial.

**Comment by j-f1** [comment]
> A downside to this approach is that one must think about the memory orderings for all of the atomic operations, but in simple cases (like a global integer counter) these accesses can just be `relaxed`.

Would it make sense to have a set of recipes/a package that contains structs wrapping `Atomic` for different use cases (like a counter), along the lines of `AtomicLazyReference` from the stdlib?

**Comment by mattmassicotte** [comment]
I'm personally pretty excited to check out built-in atomics more. The problem is we really do want to keep this document as focused as possible on helping people migrate to Swift 6 successfully without introducing more concepts than necessary. There's already an enormous amount of new stuff.

> Would it make sense to have a set of recipes/a package that contains structs wrapping `Atomic` for different use cases (like a counter), along the lines of `AtomicLazyReference` from the stdlib?

This could work great! I'm not really familiar with where other standard library documenation is going. Perhaps along side the new Mutex type?
