### ISSUE TITLE
DataRaceSafety.md Para about ‘non-isolated’ could be clearer. 

### ISSUE THREAD

**Issue by Diggory** [apple/swift-migration-guide#78]
Hello. 

In DataRaceSafety.md under the ‘[non-isolated](https://github.com/apple/swift-migration-guide/blob/main/Guide.docc/DataRaceSafety.md#non-isolated)’ section there is a para which I believe is ambiguous and could be made clearer. 

Currently it reads:

> “Data isolation guarantees that non-isolated entities cannot access the mutable state from other domains. As a result of this, non-isolated functions and variables are always safe to access from any other domain.”

What is ‘the’ mutable state in this para? Does it refer to the mutable state of _other_ domains? Or does it mean the mutable state in itself (the non-isolated domain) accessed from another domain?  

If it’s the former (which the second sentence appears to support) then might I suggest that ‘from’ in the first sentence should be replaced with ‘of’. (Or perhaps 'in', or ‘belonging to’)

So the para would read as so:

> “Data isolation guarantees that non-isolated entities cannot access the mutable state of other domains. As a result of this, non-isolated functions and variables are always safe to access from any other domain.”

**Comment by mattmassicotte** [comment]
Yeah, I completely agree.
