### ISSUE TITLE
Swift6Mode.md Add default swiftLanguage versions code

### ISSUE THREAD

**Issue by GangWoon** [apple/swift-migration-guide#84]
Hello!

I noticed that the example code doesn't show how to set the default tools language mode. 
While the package manifest section mentions it, it might be helpful to add a line in the example code as well. 
For people like me who look at the code before reading the text, this can be confusing :)

```
    ],
    // Set default swift langugae version
    swiftLanguageVersions: [.v6]
```

**Comment by mattmassicotte** [comment]
This line is not necessary though!

The example code uses 

```swift
// swift-tools-version: 6.0
```

And that sets the language mode to `6` unless explicitly override, which also happens in the same Package.swift.

**Comment by GangWoon** [comment]
Thank you so much for your kind response :)
I agree, if it's a override action, there doesn't seem to be a reason for this issue to exist.
But If the code wasn't added, it didn't build with Swift 6.0. Could it be a simple Xcode bug?

```    
swiftLanguageVersions: [.v6]
```

**Comment by GangWoon** [comment]
## Before 
<img width="681" alt="Screenshot 2024-06-18 at 07 21 21" src="https://github.com/apple/swift-migration-guide/assets/48466830/fed6fdc4-3d90-413d-bc2a-07b904458a3c">
<img width="1258" alt="Screenshot 2024-06-18 at 07 21 13" src="https://github.com/apple/swift-migration-guide/assets/48466830/a083698f-8102-4f2f-9c45-4624fd220a22">


## After
<img width="655" alt="Screenshot 2024-06-18 at 07 21 55" src="https://github.com/apple/swift-migration-guide/assets/48466830/c06a2742-08c7-4ffb-a7ce-ca594e885f1f">
<img width="1263" alt="Screenshot 2024-06-18 at 07 22 08" src="https://github.com/apple/swift-migration-guide/assets/48466830/c51c3575-0c5e-4120-bb4c-4ff51b85ce94">

**Comment by mattmassicotte** [comment]
I believe Xcode 16 beta 3 has fixed this!
