### ISSUE TITLE
Confusing explanation in "Non-isolated" section.

### ISSUE THREAD

**Issue by thai-d-v** [apple/swift-migration-guide#87]
Hello everyone! 

I find this part can be confusing. 

> ... This absence of isolation behaves just like a domain all to itself...

I understand what you want to say here, but I think it should be explained differently. Here's why:

```swift
nonisolated func work() {
  MainActor.assertIsolated()
}

nonisolated func asyncWork() async {
  MainActor.assertIsolated()
}

// on MainActor

work()
// run just fine

await asyncWork()
// Fatal error: Incorrect actor executor assumption;
// Expected 'UnownedSerialExecutor(executor: (Opaque Value))' executor.
```

- The synchronous function got isolated to the caller domain and executed outside its "imaginary non-isolated domain."
- The asynchronous function is vaguely executed somewhere else, and can be on its "imaginary non-isolated domain." 

This can be confusing because readers will probably "imagine" about the code below, where a function always is executed on its own domain.

```swift
@globalActor actor ImaginaryActor {
  static var shared = ImaginaryActor()
}

@globalActor actor ImaginaryActor_Async {
  static var shared = ImaginaryActor_Async()
}

@ImaginaryActor func otherWork() {
  ImaginaryActor.assertIsolated()
}

@ImaginaryActor_Async func otherAsyncWork() async {
  ImaginaryActor_Async.assertIsolated()
}

// on MainActor

await otherWork()
await otherAsyncWork()
// run just fine
```

I feel a bit awkward, writing this just to give my opinion on a short sentence. But hopefully it all comes across clearly.

And of course, let me know if I've misinterpreted anything.

**Comment by mattmassicotte** [comment]
I appreciate you bringing this up. I'm *really* torn here, because it kinda looks to me like this might be a compiler bug. I've filed it just in case, and I'd like to get clarification first before moving further with it.

https://github.com/apple/swift/issues/74490

**Comment by mattmassicotte** [comment]
Ok, so I have now clarified the behavior.

My confusion, and possibly yours as well, came from the fact that a top-level entry context is MainActor-isolated. But that isolation is *not* inferred by top-level functions.

Here's the key: adding `nonisolated` to `work` and `asyncWork` changes *nothing*. They already were nonisolated.

On the other hand, `otherWork` and `otherAsyncWork` *are* isolated. And because they are being called from this implicitly MainActor-context, awaits are required.

So while I agree this is confusing, you've really written something that is semantically equivlane to this:

```swift
func work() {
}

work()
```

That's allowed. The compile isolation checks will ensure this is always safe.

> Data isolation guarantees that non-isolated entities cannot access the mutable state of other domains. As a result of this, non-isolated functions and variables are always safe to access from any other domain.

**Comment by mattmassicotte** [comment]
I take it back though. If its confusing its confusing. Should look into improving the wording.

**Comment by thai-d-v** [comment]
I think I understand implicit isolation in the entry context; I just add the `nonisolated` keyword for clarification purposes.

My point is that when readers read this:

> ... This absence of isolation behaves just like a domain all to itself...

They probably expect that `work` is isolated somewhere and needs to be called by `await work()`. But in reality, it's not; we don't need `await` to call it.

**Comment by mattmassicotte** [comment]
I think you are right that this working is problematic. It is true for *asynchronous* functions, but not for synchronous ones. And that alone is probaby a good reason to rethink this.

Thanks again for filing this. Sorry it took me a while to get there.

**Comment by thai-d-v** [comment]
Even with _non-isolated asynchronous functions_, it's only _true if and only if_ each of them is always executed on a separate domain. And I'm not sure that's the case. 

Please let me know if you have the answer for this.

**Comment by thai-d-v** [comment]
Ah, I understand your point now. So it's true for _asynchronous_ functions.

**Comment by mattmassicotte** [comment]
Just because it is true in that case doesn't mean it is a good way to explain things. I definitely closed the issue prematurely.
